### ISSUE TITLE
Nox auto restart for farming biometrics

### ISSUE THREAD

**Issue by Gnoth-404** [tmarenko/mff_auto#11]
![nox](https://user-images.githubusercontent.com/61280897/99895724-09833680-2cbc-11eb-84b5-803a1d00f13a.PNG)
Which version of nox supports this feature?

**Comment by tmarenko** [comment]
It's a default warning message and has nothing to do with Nox version:
https://github.com/tmarenko/mff_auto/blob/master/lib/game/game.py#L403-L404
You should make Nox restartable via menu:
![image](https://user-images.githubusercontent.com/31345208/99902151-a5b53980-2ccc-11eb-8f2c-851b0bfb00ec.png)
and then restart bot & emulator to apply changes.
You can try older Nox (6.3.0.5) if it didn't help.

**Comment by Gnoth-404** [comment]
Thanks, unfortunately nox 6.6.1.3 isn't working. Switch back to nox 6.3.0.5 and the bot works well right now. Thanks for your help.
