### ISSUE TITLE
Some bugs I have noticed

### ISSUE THREAD

**Issue by DoTheDream** [tmarenko/mff_auto#13]
When m'kraan shard are caped the dimension mission will not go on as it will not acknowledge the prompt

Coop mission gets bugged with a message found auto play on, turning it off (although its already off obviously)

Tried putting the Blindsided mission (cyclops bios) in the bot but it will always come back saying all entries are used

Giant boss raid will get stuck after a few times of getting kicked, and if you are leader it won't start it

Also I don't know if that's an issue of my own, my emulator gets frozen from time to time and the only solution is to kill all apps and start mff again, the bot wont recognize that so it won't restart the game

**Comment by tmarenko** [comment]
> When m'kraan shard are caped the dimension mission will not go on as it will not acknowledge the prompt

Looks like devs changed order of notifications again. I know how to fix it but I need a few days to test the fix.

> Coop mission gets bugged with a message found auto play on, turning it off (although its already off obviously)

I have no problem with this even on 720p with MEDIUM graphics. What's your in game graphic settings and emulator's resolution?

> Tried putting the Blindsided mission (cyclops bios) in the bot but it will always come back saying all entries are used

It's broken because of new Epic Quest in 6.6.0. I'll release fix for it soon.

> Giant boss raid will get stuck after a few times of getting kicked, and if you are leader it won't start it

Giant boss still in beta. I've never encountered this situation so bot doesn't know how to handle "you've been kicked" situation.

> Also I don't know if that's an issue of my own, my emulator gets frozen from time to time and the only solution is to kill all apps and start mff again, the bot wont recognize that so it won't restart the game

It's emulator's & game's problem. Few updates before it was working fine. Now I usually restart game before DM/WB/WBI/DR because it gets frozen while loading.

**Comment by tmarenko** [comment]
Dimensions missions and Epic Quests should be fixed in new release: https://github.com/tmarenko/mff_auto/releases/tag/0.7.7

**Comment by DoTheDream** [comment]
> > When m'kraan shard are caped the dimension mission will not go on as it will not acknowledge the prompt
> 
> Looks like devs changed order of notifications again. I know how to fix it but I need a few days to test the fix.
> 
> > Coop mission gets bugged with a message found auto play on, turning it off (although its already off obviously)
> 
> I have no problem with this even on 720p with MEDIUM graphics. What's your in game graphic settings and emulator's resolution?
> 
> > Tried putting the Blindsided mission (cyclops bios) in the bot but it will always come back saying all entries are used
> 
> It's broken because of new Epic Quest in 6.6.0. I'll release fix for it soon.
> 
> > Giant boss raid will get stuck after a few times of getting kicked, and if you are leader it won't start it
> 
> Giant boss still in beta. I've never encountered this situation so bot doesn't know how to handle "you've been kicked" situation.
> 
> > Also I don't know if that's an issue of my own, my emulator gets frozen from time to time and the only solution is to kill all apps and start mff again, the bot wont recognize that so it won't restart the game
> 
> It's emulator's & game's problem. Few updates before it was working fine. Now I usually restart game before DM/WB/WBI/DR because it gets frozen while loading.

Adding more restarts and increasing the resolution fixed the issues my graphics are high but resolution was low for some reason.
Another issue I noticed is during the alliance battle extreme it wont click through the cinematic screen for a looong time

Thanks a lot for your help and fast replies! Keep up the good work :)

**Comment by tmarenko** [comment]
> Another issue I noticed is during the alliance battle extreme it wont click through the cinematic screen for a looong time

Yeah, I have this one too. I have some ideas how to skip this screen so wait for fix.

**Comment by tmarenko** [comment]
> alliance battle extreme it wont click through the cinematic screen

Fixed in 22353e3d6aaf5198d6f3500c00cb748e9a2f3b5a
