### ISSUE TITLE
Setup window appears, and not recognize the emulator

### ISSUE THREAD

**Issue by noramann** [tmarenko/mff_auto#20]

**Comment by tmarenko** [comment]
Any log files or additional information?

**Comment by noramann** [comment]
This is the last log, i only open start.bat -> Setup and open Nox, but nothing happens, the emulator doesn't appear on Setup.
[debug_2021-03-22--08-53-01.log](https://github.com/tmarenko/mff_auto/files/6180728/debug_2021-03-22--08-53-01.log)
![Warning](https://user-images.githubusercontent.com/81121200/111964020-138f3780-8aec-11eb-93f0-9bd31b1e89bb.JPG)

**Comment by tmarenko** [comment]
Try to remove this file: `settings\gui\game.json` and run `start.bat` again.
If it fails then send me new log from that setup.

**Comment by noramann** [comment]
[debug_2021-03-22--09-02-39.log](https://github.com/tmarenko/mff_auto/files/6180770/debug_2021-03-22--09-02-39.log)

**Comment by tmarenko** [comment]
I think one of the reason why this happens: not enough OS permissions to get emulator's process here:
https://github.com/tmarenko/mff_auto/blob/f21743da7fb02a41972a4b2bfbdfa41bef07eed0/lib/gui/widgets/setup_player.py#L95

Did you try to run `start.bat` as Administrator?

If it doesn't help you can try to create `game.json` manually.
Structure of `game.json` file for NoxPlayer:
`
{
	"timeline_team": 1,
	"mission_team": 1,
	"acquire_heroic_quest_rewards": true,
	"player_name": "NoxPlayer",
	"player_type": "NoxWindow",
	"game_app_rect": null
}
`
Replace `NoxPlayer` with your Nox's name from here:
![image](https://user-images.githubusercontent.com/31345208/111970127-041fe680-8b0c-11eb-92d6-3758442fe81c.png)

then put this `game.json` file into `settings\gui` folder and try to run the bot.
The downside of this method is that you will have empty `game_app_rect` (because bot calculates it dynamicly in setup) so no restart game/farm bios options for you.

**Comment by noramann** [comment]
When i try to run as administrator, start.bat closes in miliseconds.

**Comment by noramann** [comment]
![image](https://user-images.githubusercontent.com/81121200/111985228-45ac9380-8b04-11eb-947a-c534f7c29086.png)

**Comment by tmarenko** [comment]
Did you start the emulator before starting the bot?

**Comment by noramann** [comment]
Nope

**Comment by tmarenko** [comment]
> Nope

You should start NoxPlayer and the start the bot. Bot can't get any information from Nox Player for set up because NoxPlayer needs to be running for this.

**Comment by tmarenko** [comment]
![image](https://user-images.githubusercontent.com/31345208/111988435-8bc42000-8b21-11eb-9f9d-c9faeac10ff8.png)

You will see your running NoxPlayer then:
![image](https://user-images.githubusercontent.com/31345208/111988518-a4ccd100-8b21-11eb-8e50-3b3506bb2124.png)

**Comment by noramann** [comment]
Nothing happens, i downloaded it again and started after having the nox open, I even tried with the bluestacks.

**Comment by tmarenko** [comment]
> Nothing happens, i downloaded it again and started after having the nox open, I even tried with the bluestacks.

You can simply delete `settings\gui\game.json` to start Setup again, don't need to redownload it.

Well, maybe the other reason why this happens is something went wrong with getting key handle from Nox.
You can test by editing this file `lib\players\android_emulator.py` at 157 line here:
https://github.com/tmarenko/mff_auto/blob/f21743da7fb02a41972a4b2bfbdfa41bef07eed0/lib/players/android_emulator.py#L154
Replace this line with `keys_found = True` (make sure to keep spaces at the start of the line same) and run Setup again.

Also, what's your OS, OS language and NoxPlayer version?

**Comment by noramann** [comment]
Putting keys_found = True worked, thanks

**Comment by tmarenko** [comment]
> Putting keys_found = True worked, thanks

Well it's not a real fix because now bot doesn't know how to send keystrokes into emulator now (i.e. you can't use "restart game" function).
If you still need ability to restart game, please tell about OS and NoxPlayer version. I'll try to test them myself sometimes later.

**Comment by noramann** [comment]
Windows 10 and Nox Version 7.0.1.0

**Comment by tmarenko** [comment]
I couldn't reproduce this issue with brand new Windows 10 Home Edition and NoxPlayer.
With clean setup NoxPlayer always has `Qt5QWindowToolSaveBits` handler for keys.
If you will found anything new or related to this issue then reopen it.
