### ISSUE TITLE
Danger Room (Another User Cancellation)

### ISSUE THREAD

**Issue by dbzdivik** [tmarenko/mff_auto#22]
Hi,

Howz everything going around you???

1. There is been an issue in code whenever we are in Danger Room and another user left the game Bot doesn't check for that notification. 

2. Also while playing if there is a Network Error message popup.. Maybe a simple check for 2-3 times would be fine after that game would close auto.

Thanks

**Comment by tmarenko** [comment]
Yeah, I've noticed this behaviour too.
Should be fixed in https://github.com/tmarenko/mff_auto/commit/ff5230b4eb2b4647abafcd21147adbcaf8ce82c1 but I still testing it.

**Comment by dbzdivik** [comment]
Ok...
What about  
![image](https://user-images.githubusercontent.com/7036189/115110605-e6725f80-9f99-11eb-889e-5f159a984ef2.png)

**Comment by tmarenko** [comment]
Never seen this notification before. When does it happen?

**Comment by dbzdivik** [comment]
this happens when a connection timeout happens for a request... either due to net or firewalls

**Comment by tmarenko** [comment]
Added in https://github.com/tmarenko/mff_auto/commit/341157420fa0c465b41f305167e858a1254371db

**Comment by dbzdivik** [comment]
> Ok...
> What about
> ![image](https://user-images.githubusercontent.com/7036189/115110605-e6725f80-9f99-11eb-889e-5f159a984ef2.png)

This also changed in new UI

**Comment by tmarenko** [comment]
Sure. All UI fixes for 7.0.0 will be in https://github.com/tmarenko/mff_auto/issues/23
But I think I'll disable `handle network errors` feature for now because it slows down all text recognition in general.
I need to fix UI for 7.0.0 asap so `handle network errors` feature will be probably after next release.

**Comment by dbzdivik** [comment]
haha not a problem

**Comment by dbzdivik** [comment]
Closing for follow up  in #29
