### ISSUE TITLE
0.8.3 - issues

### ISSUE THREAD

**Issue by meakashi** [tmarenko/mff_auto#24]
The bot constantly relaunches the app if you tick the 'farm shifter reward' option in Epic Quest -> First Family -> Twisted World.
This is because this stage doesn't actually have a shifter.
(This stage rewards are overall trash. But that's not your fault).
Thanks

**Comment by tmarenko** [comment]
If you've only started this Epic Quest then yes, Twisted World doesn't have a shifter. But upon further Epic Quest completion it will appear in both missions:
![image](https://user-images.githubusercontent.com/31345208/116981069-b6cc9280-accf-11eb-8219-f1d25196b420.png)

Just don't toggle 'farm shifter reward' for now

**Comment by meakashi** [comment]
Thanks!
