### ISSUE TITLE
0.8.4 issues

### ISSUE THREAD

**Issue by Vodka4882** [tmarenko/mff_auto#25]
Скачал новый клиент - 0.8.4. Но в 8.3 та же ситуация была, кажется.
Похоже, клиент не проверяет наличие шифтера в эпических квестах Стрэнджа. В частности, в dark advent. Из-за чего не перезапускает клиент, когда Клея не появляется.
Там вообще всё сложно, так как био шифтеров меньше, чем био основного соперника

**Comment by meakashi** [comment]
После боя в Co-op Play на окне, где выводятся итоги боя (Mission success + проценты урона, нанесенные боссу), клиент зацикливается, вновь и вновь повторяя команду debug - notifications - After mission notifications was closed.

**Comment by meakashi** [comment]
Squad battle - daily random не работает. В окне, где по центру большой экран, а по краям команды, клиент уходит в бесконечный цикл с той же дебажной командой, что и выше.

**Comment by tmarenko** [comment]
> Похоже, клиент не проверяет наличие шифтера в эпических квестах Стрэнджа. В частности, в dark advent.

Если я правильно помню, с Клеей достаточно пройти 10 доступных миссий и все 3 био шифтера должны выпасть 100%. Может это поменяли, перепроверю потом.


> клиент зацикливается, вновь и вновь повторяя команду debug - notifications - After mission notifications was closed.

Нужен логфайл

**Comment by Vodka4882** [comment]
Спасибо за ответы. Видимо, плавающая ошибка. Иногда случается, но стоит включить запись видео, так сразу проблема уходит. В следующий раз постараюсь писать о таком только когда будут логи и видео, чтобы не отвлекать. Спасибо еще раз
