### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by Khapato** [tmarenko/mff_auto#26]
Your work is impressive! One thing that would be really nice is to auto dispatch missions and auto-reset if no reward shown in the screen until a certain amount of time has passed, specially for cards.

**Comment by tmarenko** [comment]
I'm glad that my project is helping someone 😃

> auto dispatch missions and auto-reset if no reward shown

Currently there is no functionality for checking the rewards and I'm not sure even how to implement it.
I might make dispatch mission runner that runs certain mission for N times or infinity time without wasting energy (farming EXP/uniform EXP), but I'm realy do not understand why would you need to check mission's rewards and why would you farm cards in dispatch missions in the first place.
