### ISSUE TITLE
Daily Trivia 

### ISSUE THREAD

**Issue by KnightM1** [tmarenko/mff_auto#27]
Проблема, дейли тривиа решает только первый вопрос, на втором останавливается и перепрыгивает на следующее задание в списке.  Почему так?

**Comment by tmarenko** [comment]
У меня работает все отлично, нужен лог-файл или видео-запись, по описанию проблемы не ясно, что не так может идти.
Видео-запись была добавлена в 0.8.4, находится в меню в левом верхнем углу (Video Recorder). Запись надо включать **до** запуска заданий, чтобы был захват всех действий бота.

**Comment by KnightM1** [comment]
[2021-05-12--21-32-46.log](https://github.com/tmarenko/mff_auto/files/6468433/2021-05-12--21-32-46.log)
https://youtu.be/Pflbit6pBUk
И так всегда, скачал новую сборку с сайта уже, не помогло

**Comment by tmarenko** [comment]
Судя по всему после первого ответа, не удается найти `DAILY_TRIVIA_TODAY_TEXT` опять, хотя с видео видно, что все в правильном месте захватывается. 
У меня такой проблемы вообще нет, данный UI вообще с легкостью ловится и на разрешении ниже с качеством картинки хуже, чем указано в логе (720p).
На компьютере случаем не были установлены какие-либо другие версии Tesseract, кроме той, которая идет в комплекте с ботом?
Если нет, то предлагаю попробовать поиграться с параметром `image_threshold` у `DAILY_TRIVIA_TODAY_TEXT` в файле `settings\ui\daily.json`, конкретно вот про эту строку идет речь: https://github.com/tmarenko/mff_auto/blob/master/settings/ui/daily.json#L171
Ее надо поменять на произвольное значение, например 100, 110, 130, 140 и т.д. перезапустить бота и посмотреть, исправляет ли это проблему.

**Comment by tmarenko** [comment]
Для удобства еще стоит создать папку `tesseract` в папке `logs`, бот будет сохранять туда файл под названием `daily_trivia_today_text.png`, его тоже стоит проанилизировать, видно ли там этот текст или нет.

**Comment by KnightM1** [comment]
После смены параметра на 130 помогло. Такая же проблема бывает с сквад батлом, оно его проходит, и на этот моменте стопится, если нажать ручками домой, программа дальше работает
![Nox_5vMGOFMq8w](https://user-images.githubusercontent.com/81584302/118308647-e1e78b00-b4f4-11eb-8161-47541c1589cb.png)

**Comment by tmarenko** [comment]
> Такая же проблема бывает с сквад батлом, оно его проходит, и на этом моменте стопится, если нажать ручками домой, программа дальше работает

`SB_BATTLE_POINTS` : https://github.com/tmarenko/mff_auto/blob/master/settings/ui/squad_battles.json#L256

> С коопом такая же проблема

Для коопа в ближайщее время будет фикс дополнительный, есть проблема, что иногда не замечает конец битвы.

**Comment by KnightM1** [comment]
> Самое странное, что ни проблема с trivia, ни с co-op у меня не воспроизводится. Текст удачно обрабатывается даже с более низким разрешением экрана, поэтому я не могу понять даже в чем проблема.

Я уже сделал игру в Full HD, все ровно не помогло, изменение параметра помогло.

**Comment by tmarenko** [comment]
> Я уже сделал игру в Full HD, все ровно не помогло, изменение параметра помогло.

Если есть возможность, то хотелось бы увидеть файл `daily_trivia_today_text.png` из `logs\tesseract` при значении 120.
То есть вернуть значение как было, запустить, посмотреть что бот опять застрял и сюда скинуть файл этот. Может что-то прояснится с обработкой изображения

**Comment by KnightM1** [comment]
> Если есть возможность, то хотелось бы увидеть файл `daily_trivia_today_text.png` из `logs\tesseract` при значении 120.
> То есть вернуть значение как было, запустить, посмотреть что бот опять застрял и сюда скинуть файл этот. Может что-то прояснится с обработкой изображения

Хорошо, после сброса сделаю. Кстати такая же проблема бывает еще с ворлд босс инвасион, через раз, бывает нормально проходит 1 этап, если ставить все 5, то виснет по любому,  это тоже что бы поправить можно параметр изменить?

**Comment by tmarenko** [comment]
> Хорошо, после сброса сделаю. Кстати такая же проблема бывает еще с ворлд босс инвасион, через раз, бывает нормально проходит 1 этап, если ставить все 5, то виснет по любому на моменте получения я сундука, это тоже можно поправить если параметр изменить?

https://github.com/tmarenko/mff_auto/blob/master/settings/ui/world_boss_invasion.json#L675

После любого следующего обновления изменения в этих файлах сотрутся, поэтому если какое-то значение помогает и работает, то стоит об этом сюда написать, чтобы сделать изменения в файлах проекта для всех

**Comment by KnightM1** [comment]
> После любого следующего обновления изменения в этих файлах сотрутся, поэтому если какое-то значение помогает и работает, то стоит об этом сюда написать, чтобы сделать изменения в файлах проекта для всех

Хорошо, я меняю то что работает со сбоями на 130, вроде помогает, после сброса запущу все задания, если пройдет без проблем, отпишусь.

**Comment by KnightM1** [comment]
С Сквадом проблема решилась окончательно, с вторжением странная штука, чаще всего останавливается если проходить все этапы почти 100%, если 1 бывает работает нормально, бывает останавливается, пробовал разные цифры 115 120 125 130.

**Comment by tmarenko** [comment]
Скорее всего присутствует действительно какая-то проблема при анализе изображений. SB_BATTLE_POINTS в 130 для меня не срабатывает вообще.
Предполагаю, что есть какая-то проблема с версией Tesseract, либо с цветовым профилем внутри Windows (может бот путает RGB с BGR, было б очень похоже), но без анализа файлов из `logs\tesseract` точно сказать невозможно.

**Comment by Vodka4882** [comment]
Там добавили новый вопрос про то, где можно крафтить всякие ништяки с ответом Craft

**Comment by tmarenko** [comment]
> Там добавили новый вопрос про то, где можно крафтить всякие ништяки с ответом Craft

https://github.com/tmarenko/mff_auto/commit/28c024e878f57692cb13ccbf3dbd9f61122be49d

**Comment by tmarenko** [comment]
https://github.com/tmarenko/mff_auto/issues/27#issuecomment-848906514
