### ISSUE TITLE
Feature Enhancement

### ISSUE THREAD

**Issue by dbzdivik** [tmarenko/mff_auto#3]
1. World Boss Invasion
> As they are Repeated Every Week and Have specific Mission Types Like only Combat Type or 4+ Female Character. I think setting/Team for a particular mission can be set.
> Also in it gets stuck in casting co-op skill only instead of that use normal skills.

2. Alliance Battle
> Same goes for alliance battle there should be a team bonus according to the daily mission or can pre-define team based on that like if superheroes + combat then only select these characters.

3. Some Epic Quests also
> Like needed to enhance iso for that needed to play Doctor Strange or Fantastic Four Epic Quests 
> or instead of that if needed to farm bios or Materials.

**Comment by tmarenko** [comment]
1.  > I think setting/Team for a particular mission can be set.

    True, this can be done via filters in "Select characters' window. I'll start working on it but it won't be released soon: this feature should be tested over a few weeks to check all different rules.

    > Also in it gets stuck in casting co-op skill only instead of that use normal skills.

    I believe I fixed similar bug a few weeks back. Can you share log files with this problem?
2. Pre-defined teams will be introduced in 6.4.0 game's update (devs are doing rework of Alliance Battle). I'll look into it after game's update.
3. Year ago this game modes was available through Content Board. Now, going to Epic Quest missions requires to open Mission Selector and scroll to desired Epic Quests. This means that when devs add new Epic Quest then all previous UI settings would be useless.
So yes, these missions can be added but they requires high maintenance after each new Epic Quest.

P.S. Don't mind to click 'Star' button on top of this page if you're enjoying the project =)

**Comment by dbzdivik** [comment]
>    True, this can be done via filters in "Select characters' window. I'll start working on it but it won't be released soon: this feature should be tested over a few weeks to check all different rules.

>    I believe I fixed similar bug a few weeks back. Can you share log files with this problem?

OK for both but Co-oP should be removed from the Invasion battle until unless mission required.

> 2. Pre-defined teams will be introduced in 6.4.0 game's update (devs are doing rework of Alliance Battle). I'll look into it after game's update.

OK have to wait for 6.4.0

> 3 Year ago this game modes was available through Content Board. Now, going to Epic Quest missions requires to open Mission Selector and scroll to desired Epic Quests. This means that when devs add new Epic Quest then all previous UI settings would be useless.
>    So yes, these missions can be added but they requires high maintenance after each new Epic Quest.

I think like training OCR for recognizing Missions, Epic Quest Banner can also train like that.

> P.S. Don't mind to click 'Star' button on top of this page if you're enjoying the project =)

Done

**Comment by tmarenko** [comment]
> but Co-oP should be removed from the Invasion battle until unless mission required.
Why? `ManualBattleBot` is designed to cast any available bonus skill (COOP or Danger Room's) and then proceed to cast character's skills without any timeout.
> Epic Quest Banner can also train like that.
Yes. I'm just saying that it's hard to do (20 total missions in all Epic Quests) and also it's hard to maintain UI elements because each new Epic Quest will make them obsolete. Still going to do this feature =)

**Comment by dbzdivik** [comment]
> Why? `ManualBattleBot` is designed to cast any available bonus skill (COOP or Danger Room's) and then proceed to cast character's skills without any timeout.

Hmm, will try to collect the log where it sticks again on world boss invasion.

> Yes. I'm just saying that it's hard to do (20 total missions in all Epic Quests) and also it's hard to maintain UI elements because each new Epic Quest will make them obsolete. Still going to do this feature =)

I think for starter the Last level of every quest can be implemented like for 
Doctor strange => 6
X-Men => 4
DeadPool => 2
FF4 => 4
GG => 2

**Comment by tmarenko** [comment]
Added all codes and UIs for Epic Quests in 4aea3baf97752e226d3fe4f6e5cf93e943a951d4
Still trying to figure out how to make it inside GUI. Mode selector looks so long if I'd add it:
![image](https://user-images.githubusercontent.com/31345208/93261618-9c2ec300-f7ab-11ea-8ad9-e0bd03122376.png)

May be tabs will help

**Comment by dbzdivik** [comment]
I think instead of that Button in quickstart can be added to Farm Bios or Material
2 Buttons:- Farm Bios & Materials (ISO and URU)
>1. Farm Bios Button Click (a second form like adding mission queue asking which Character to be farmed which is maxed 10 times)
>2. Material collection same goes 2nd forms with 3 Checkboxes ISO which can be harvested in 2 different stages and the same goes for URU

**Comment by tmarenko** [comment]
> I think instead of that Button in quickstart can be added to Farm Bios or Material.

I want to add ability to queue these Epic Quest missions so Quick Start does not fit here.
> Also which IDE you're using to build this project?

PyCharm Community Edition

**Comment by tmarenko** [comment]
> Also in it gets stuck in casting co-op skill only instead of that use normal skills.

I added locking coop skill and reloading of basic skills in case their labels was interrupt by something. Should be more stable now.

> Pre-defined teams will be introduced in 6.4.0 game's update (devs are doing rework of Alliance Battle). I'll look into it after game's update.

Your last characters that was used previously now will be on top with new "Recent" label. Bot will be picking them.

All of this and 6.4.0 support in new release: https://github.com/tmarenko/mff_auto/releases/tag/0.5.3

> Added all codes and UIs for Epic Quests

Still working on GUI part for it.

**Comment by dbzdivik** [comment]
World Boss Issue: If I've already selected Heroes Like on Selector 1 then the respective selector on co-op player should be used.

**Comment by tmarenko** [comment]
> World Boss Issue: If I've already selected Heroes Like on Selector 1 then the respective selector on co-op player should be used.

Is there any reason to not use always the same allies for all teams?

**Comment by dbzdivik** [comment]
> Is there any reason to not use always the same allies for all teams?
Yes, Like for 1st selection I'm using Wolverine so I can set co-op help with Wolverine and for 2nd I had to select different Characters but will be needing Wolverine for support and so on.

**Comment by tmarenko** [comment]
Not easy to do and it will lead to more troubles and unnecessary checks for team setups. I think I'll leave it as it is. 
So my advice is to use same allies for all teams. Skipping one or two characters for allies setup (if they were setup in team instead) is not a big deal for this game mode.

**Comment by tmarenko** [comment]
Tried tab layout same as in game... Not sure if it looks okay. Too much tabs in my opinion

![image](https://user-images.githubusercontent.com/31345208/93506560-1fbfef80-f925-11ea-9e93-c0b694c71fb1.png)

**Comment by dbzdivik** [comment]
> Not easy to do and it will lead to more troubles and unnecessary checks for team setups. I think I'll leave it as it is.
> So my advice is to use same allies for all teams. Skipping one or two characters for allies setup (if they were setup in team instead) is not a big deal for this game mode.

Ok can adjust as on

**Comment by dbzdivik** [comment]
> Tried tab layout same as in game... Not sure if it looks okay. Too much tabs in my opinion
> 
> ![image](https://user-images.githubusercontent.com/31345208/93506560-1fbfef80-f925-11ea-9e93-c0b694c71fb1.png)

Hmm definitely too much tabs give a pause. I'll see what can be done but after this weekend.

**Comment by dbzdivik** [comment]
> ![image](https://user-images.githubusercontent.com/31345208/93506560-1fbfef80-f925-11ea-9e93-c0b694c71fb1.png)

Can you share UI for this?

Also what about SikuliX ??

**Comment by tmarenko** [comment]
> Can you share UI for this?

[queue_editor_window_tmp.txt](https://github.com/tmarenko/mff_auto/files/5256355/queue_editor_window_tmp.txt)

> what about SikuliX ?

What about it?

**Comment by dbzdivik** [comment]
SikuliX => Jython Automation using OpenCV

BTW getting this error why ?
`Error in boxClipToRectangle: box outside rectangle
Error in pixScanForForeground: invalid box`

**Comment by tmarenko** [comment]
> Jython Automation using OpenCV

Sorry, still don't understand. What are you suggesting to do with that?

> Error in boxClipToRectangle: box outside rectangle Error in pixScanForForeground: invalid box

Tesseract's bug: https://github.com/tesseract-ocr/tesseract/issues/427
Does nothing for the bot though so doesn't even get logged

**Comment by tmarenko** [comment]
> Tab UI I think its too much

I think this looks fine:
![image](https://user-images.githubusercontent.com/31345208/93881528-b571cb00-fce7-11ea-8f83-bafed8c52fe1.png)

**Comment by dbzdivik** [comment]
Kinda Messy.

What about in Select Mode Combo add 2 option to Farm Bio's and Material
When Farm Bios is selected Multiple Check Box visible for (Nebula , Dark Hawk, Punisher etc) all bios from epic quest.
Similarly when Farm Materials is selected M'kraan, ISO & URU

By this Mission Queue will only have 2 more options Farm Bios [All Bio's from EPIC Quest / (Strom,Beast, etc..)] and so on

**Comment by tmarenko** [comment]
> What about in Select Mode Combo add 2 option to Farm Bio's and Material

Single queue item should represent one mission class. Otherwise there will be inconvenience what'd be executed.
I've put all Epic Quests into one submenu and left all others missions in main menu. Here how it looks now:

![image](https://user-images.githubusercontent.com/31345208/94005706-51aed700-fda7-11ea-81a5-0a23eb9ba789.png)

**Comment by dbzdivik** [comment]
> Single queue item should represent one mission class. Otherwise there will be inconvenience what'd be executed.

I didn't get you.
BTW what I'm thinking

![image](https://user-images.githubusercontent.com/7036189/94007085-84b09500-fdbe-11ea-9ba0-c2b59dc45ae4.png)

**Comment by tmarenko** [comment]
> I didn't get you.

One queue item = one execution of single mission. Here: https://github.com/tmarenko/mff_auto/blob/master/lib/gui/widgets/queue_item_editor.py#L397-L398
Doing your way there will be problems:
- is one item added to queue or 3? (from screenshot example when Satana+Hellstorm+Storm are selected)
- what to do with 'Edit' button if it's 3 items? edit only one or all of them?
- if it's one item then how to apply shifter farming (Cleo f.e.) for non-shifter missions (Storm f.e.)?
- if it's one item then there should be difficulty selectors for every missions with difficulty available
- filtering missions with new classes will lead to overpopulating of this filter-classes (BIO, Shifter's BIO, Feathers, URUs, ISOs, Gear Kits, Shards, Obelisks). Hard to maintain and to resolve all "Add/Edit/Run" parameters.

> Also according to your GUI, It will increase Mission Queue Items which will become messy.

Do you really need to add all 29 Epic Quests missions at the same time? Also you don't want to run them all at the same time because you run out of boost points and your rewards become worse.


For long Missions Queue there is solution to create multiple tabs for different queues:
![image](https://user-images.githubusercontent.com/31345208/94009095-a7d24900-fdac-11ea-8880-021e448331aa.png)

So you can have one tab for your daily mission completion, other tab for farming epic quests and etc.

**Comment by dbzdivik** [comment]
OK, now I get it.
Also, would you be adding a limit of adding missions to queue list to avoid overflooding ?

**Comment by tmarenko** [comment]
> would you be adding a limit of adding missions to queue list to avoid overflooding ?

Probably no. I'll let user to decide whether he want to have a long queue or not.

Check out new release with all available Epic Quests: https://github.com/tmarenko/mff_auto/releases/tag/0.5.4

**Comment by tmarenko** [comment]
> As they are Repeated Every Week and Have specific Mission Types Like only Combat Type or 4+ Female Character. I think setting/Team for a particular mission can be set.

I've checked and it looks like there are different rules for each week. A week ago was Ulik was with "no restrictions" rule, today's Ulik is with "less than 3 male characters".
I'm not sure how to determine current boss's rule in order to setup perfect team.

**Comment by dbzdivik** [comment]
> > would you be adding a limit of adding missions to queue list to avoid overflooding ?
> 
> Probably no. I'll let user to decide whether he want to have a long queue or not.
> 
> Check out new release with all available Epic Quests: https://github.com/tmarenko/mff_auto/releases/tag/0.5.4

Cool But there should be a limit like the only max. 6 difficulties and max 10 times stage can be repeated

**Comment by tmarenko** [comment]
> Cool But there should be a limit like the only max. 6 difficulties and max 10 times stage can be repeated

You can run more than 10 stages if you want to (f.e. farm materials or farm character/uniform exp). 
If you enter wrong difficulty then max difficulty (4 or 6) would be applied.

**Comment by dbzdivik** [comment]
>`
2020-09-24 19:28:53,806 - queue_manager - DEBUG - Running DANGEROUS SISTERS with settings: {'times': 10}
2020-09-24 19:28:55,171 - epic_quests - INFO - Dangerous Sisters: 10 stages to complete.
2020-09-24 19:29:02,688 - epic_quests - INFO - No more stages for Dangerous Sisters.
2020-09-24 19:29:04,451 - missions - DEBUG - After mission notifications was closed: False
2020-09-24 19:29:05,667 - missions - DEBUG - After mission notifications was closed: False
2020-09-24 19:29:06,891 - missions - DEBUG - After mission notifications was closed: False
2020-09-24 19:29:09,157 - queue_manager - DEBUG - Running COSMIC RIDER with settings: {'times': 10}
2020-09-24 19:29:10,519 - epic_quests - INFO - Cosmic Rider: 10 stages to complete.
2020-09-24 19:29:18,150 - epic_quests - INFO - No more stages for Cosmic Rider.
2020-09-24 19:29:20,020 - missions - DEBUG - After mission notifications was closed: False
2020-09-24 19:29:21,263 - missions - DEBUG - After mission notifications was closed: False
2020-09-24 19:29:22,493 - missions - DEBUG - After mission notifications was closed: False
2020-09-24 19:29:24,710 - queue_manager - DEBUG - Running WINGS OF DARKNESS with settings: {'times': 10, 'difficulty': 4}
2020-09-24 19:29:26,041 - epic_quests - INFO - Wings of Darkness: 10 stages to complete.
2020-09-24 19:29:32,985 - game - DEBUG - Loading circle is on screen.
2020-09-24 19:29:34,076 - missions - DEBUG - Selecting team: SELECT_TEAM_5
2020-09-24 19:29:35,141 - game - DEBUG - Loading circle is on screen.
`

**Comment by tmarenko** [comment]
> EPIC QUEST not working correctly

Fixed in https://github.com/tmarenko/mff_auto/commit/c9f02529b4eef416974a2e0ebcec5abc37a69560
