### ISSUE TITLE
closes just after launching

### ISSUE THREAD

**Issue by StarLorde93** [tmarenko/mff_auto#32]
i tried to launch it but its not working, i'm not a expert in this so i will just share the log file, please help.

[2021-07-02--22-45-06.log](https://github.com/tmarenko/mff_auto/files/6756102/2021-07-02--22-45-06.log)

**Comment by tmarenko** [comment]
I'm actually don't know what even happened here =)
Looks like while trying to access the version file from repository (https://raw.githubusercontent.com/tmarenko/mff_auto/master/version.py) you've encountered some odd error with InvalidURL exception. This is functionality of Auto-Updater which is checking for new updates from repo on the start but something went wrong.
I'm not sure what is wrong with updater code so I've just added handler for this exception. You can try to apply changes from https://github.com/tmarenko/mff_auto/commit/fbce4e3772b38327b8f33457c8947d3790abc608 manually and send log file with information about this error. Changes from https://github.com/tmarenko/mff_auto/commit/fbce4e3772b38327b8f33457c8947d3790abc608 will disable Auto-Update functions for you if the error will continue to occur so make sure to send new log file after applying this changes.

**Comment by StarLorde93** [comment]
never mind i got frustrated and reinstalled my windows so now i'm past this point but another problem occured which is mentioned in #28 so now i'm installing v7.0.1.0
