### ISSUE TITLE
Предложение: игнор условий Вторжения мирового босса

### ISSUE THREAD

**Issue by Vodka4882** [tmarenko/mff_auto#33]
Очень часто сливаю лишнюю энергию в World boss invasion. Если не затруднит, пожалуйста, добавь галочку в опции: "Co-op mission ignore" или подобную, чтобы не учитывалось условие для получение доп. награды в этот день.
А то в случае со злодеями и женскими персонажами очень быстро заканчиваются персы и приходится играть вручную.
Спасибо!

**Comment by tmarenko** [comment]
Added in https://github.com/tmarenko/mff_auto/commit/b95d333f6159efcfd3a211be2696937999f43d42
Release in https://github.com/tmarenko/mff_auto/releases/tag/0.8.6
