### ISSUE TITLE
blank setup window

### ISSUE THREAD

**Issue by VincentWick** [tmarenko/mff_auto#34]
i tried followed your installation but after the start.bat there's nothing. it's just says "Run Android Emulator with MFF intalled and select emulator's window from the list below selected:"
![Desktop Screenshot 2021 07 19 - 09 39 17 65](https://user-images.githubusercontent.com/83640831/126090758-d211540f-9989-4ca4-9861-517bcc7fa431.png)

**Comment by tmarenko** [comment]
Which emulator (BlueStacks / NoxPlayer) and which its version are you using?

**Comment by VincentWick** [comment]
I use bluestack 5

**Comment by tmarenko** [comment]
Try to use BlueStacks 4 or NoxPlayer 7.0.1.0.
I haven't tested BlueStacks 5 yet so it's possible that there issues with capturing.

**Comment by VincentWick** [comment]
thanks. it worked now

**Comment by tmarenko** [comment]
BlueStacks 5 support added in https://github.com/tmarenko/mff_auto/commit/b09e5da04631bd8a1bc121a0fc4b49679ea16e49
Released in https://github.com/tmarenko/mff_auto/releases/tag/0.8.7
