### ISSUE TITLE
BlueStacks

### ISSUE THREAD

**Issue by KnightM1** [tmarenko/mff_auto#35]
Проблема в том что на этом эмуляторе почему то не работает скролл в программе, хотя мышкой все ок, вот видео.
В чем может быть проблема? Проблема была и до обновы
https://www.youtube.com/watch?v=9oDg01f-mmU

**Comment by tmarenko** [comment]
Эта ошибка наблюдается на BlueStacks 5ой версии, верно?
Если да, то фикс вот: https://github.com/tmarenko/mff_auto/commit/8346cf79707a9c430a5bee324341d5acdf8cb518

**Comment by KnightM1** [comment]
> Эта ошибка наблюдается на BlueStacks 5ой версии, верно?
> Если да, то фикс вот: [8346cf7](https://github.com/tmarenko/mff_auto/commit/8346cf79707a9c430a5bee324341d5acdf8cb518)

Помогло, спасибо.
