### ISSUE TITLE
Feature Request - Free Hero Chest, Support Shop

### ISSUE THREAD

**Issue by dwiza3962** [tmarenko/mff_auto#36]
Hi,

Thank you for the wonderful automater for MFF.   This helps me save a lot of time in my daily farming.   I have a couple of features I'd like to request that may not be too hard.

- Add Obtaining Free Hero Chest to Daily Actions - I've amassed most of all the Free To Play characters, and usually just want the bios from this.    
- Add buying UUK (Uniform Upgrade Kits) from the Support Shop Daily - Usually try to do this once per day and would be great to automate this.

**Comment by tmarenko** [comment]
> Add Obtaining Free Hero Chest to Daily Actions - I've amassed most of all the Free To Play characters, and usually just want the bios from this.

Added in https://github.com/tmarenko/mff_auto/commit/0776729d0a08e17f03d56f01a5cb268f1fcbf1ec

> Add buying UUK (Uniform Upgrade Kits) from the Support Shop Daily - Usually try to do this once per day and would be great to automate this.

Added in https://github.com/tmarenko/mff_auto/commit/ccb062c6a9240366d9958cda0ff8dc667d531e54

**Comment by dwiza3962** [comment]
This is great, thank you so much for implementing this.   Will give this a try in a bit.

**Comment by tmarenko** [comment]
Fixed store opening and queue loading: https://github.com/tmarenko/mff_auto/commit/805bb7659f672e23bd94c59293b648840c188134 https://github.com/tmarenko/mff_auto/commit/805bb7659f672e23bd94c59293b648840c188134 

Adding Support Shop revealed issue with MultiCheckbox loading into the queue =)
Still need to test this new features before adding to release, new release will be maybe until the end of the week.

**Comment by dwiza3962** [comment]
Free Hero Chest doesn't appear to be working, I'll try with your latest updates though.    Also on support shop, only buys one.   Can we get an option to supply the amount to buy?

**Comment by tmarenko** [comment]
> Free Hero Chest doesn't appear to be working, I'll try with your latest updates though. Also on support shop, only buys one.

Please attach log file or provide additional information.

> Can we get an option to supply the amount to buy?

Do you mean buying not all available items at once (without clicking MAX button)?

**Comment by tmarenko** [comment]
> Add Obtaining Free Hero Chest to Daily Actions - I've amassed most of all the Free To Play characters, and usually just want the bios from this.
Add buying UUK (Uniform Upgrade Kits) from the Support Shop Daily - Usually try to do this once per day and would be great to automate this.

Released in https://github.com/tmarenko/mff_auto/releases/tag/0.8.9
