### ISSUE TITLE
Задержка старта игры

### ISSUE THREAD

**Issue by Vodka4882** [tmarenko/mff_auto#37]
Подскажи, пожалуйста, какая настройка отвечает за то, чтобы увеличить время между закрытием и открытием игры при рестарте?
Суть: При фарме биометрик, когда нет шифтера, бот закрывает игру и тут же запускает её. Но при этом эмулятор малость тупит и повторно активирует закрытие приложений.
Если что, эта проблема у меня на всех версиях бота, начиная с версии игры 7.0. До этого не играл.
Спасибо.

**Comment by tmarenko** [comment]
https://github.com/tmarenko/mff_auto/blob/master/lib/game/game.py#L473

Вынести как настроечный параметр?

**Comment by Vodka4882** [comment]
Спасибо за ответ и за предложение. Если ты сам с такой ситуацией не
сталкивался никогда, и никто не жаловался, то не надо, наверное. А так -
легко запомнить, где меняется.

чт, 5 авг. 2021 г. в 13:48, Timofey Marenko ***@***.***>:

**Comment by tmarenko** [comment]
Оставлю тогда как есть, пока нет решения для https://github.com/tmarenko/mff_auto/issues/28. 
Главное помнить, что при каждом обновлении, изменения в файле будут затираться и надо будет вручную менять.
