### ISSUE TITLE
Добавить функции.

### ISSUE THREAD

**Issue by KnightM1** [tmarenko/mff_auto#39]
Привет, а можно ли добавить в программу пару надоедливых ежедневных действий?
Например забрать и запросить ресурсы/био у союза, и донат голды/жетонов в союз?
Возможность покупать в магазине союза энергию через программу тоже пригодилось бы, но это уже не так важно.
Спасибо!
п.с.: Еще бы смена выбора страйкеров не помешала, а то когда прога бьет мефа/кнула, 1 раз юзает 1 команду страйкеров, а дальше без страйкеров бьет, хорошо бы юзала все 5 команд страйкеров.

**Comment by tmarenko** [comment]
> Еще бы смена выбора страйкеров не помешала, а то когда прога бьет мефа/кнула, 1 раз юзает 1 команду страйкеров, а дальше без страйкеров бьет, хорошо бы юзала все 5 команд страйкеров.

Было добавлено уже (https://github.com/tmarenko/mff_auto/issues/9#issuecomment-898596548), в релиз пока еще не попало.

> Например забрать и запросить ресурсы/био у союза, и донат голды/жетонов в союз?
Возможность покупать в магазине союза энергию через программу тоже пригодилось бы, но это уже не так важно.

Донат и покупку энергии довольно легко сделать, забрать ресурсы тоже. С запросом сложнее, т.к. там довольно много позиций и их надо скроллить (посмотрим, получится ли хоть что-то сделать).

**Comment by tmarenko** [comment]
> Например забрать и запросить ресурсы/био у союза, и донат голды/жетонов в союз?
Возможность покупать в магазине союза энергию через программу тоже пригодилось бы, но это уже не так важно.

Released in https://github.com/tmarenko/mff_auto/releases/tag/0.8.10
