### ISSUE TITLE
[Bug] World Boss & Co-oP Play

### ISSUE THREAD

**Issue by dbzdivik** [tmarenko/mff_auto#4]
1. If Normal mode is selected in Mission Queue and if Ultimate stage is selected then bot will start playing Ultimate stage instead of normal mode.
2. Bot doesn't click on Co-Op skill while playing World Boss.
3. If stages are completed bot start play again In training mode instead of quitting

**Comment by dbzdivik** [comment]
Unable to Play CO-OP Play 

2020-09-23 10:47:36,621 - coop - INFO - Coop play: 5 stages available
2020-09-23 10:47:37,492 - game - DEBUG - Loading circle is on screen.
2020-09-23 10:47:50,814 - coop - WARNING - Can't deploy character for COOP. Probably you run out of available. Exiting
2020-09-23 10:47:50,815 - coop - INFO - No more stages for coop play.
2020-09-23 10:47:53,129 - missions - DEBUG - After mission notifications was closed: False
2020-09-23 10:47:54,494 - missions - DEBUG - After mission notifications was closed: False
2020-09-23 10:47:55,738 - missions - DEBUG - After mission notifications was closed: False
2020-09-23 10:47:58,513 - queue_manager - DEBUG - Queue completed.

**Comment by tmarenko** [comment]
> Unable to Play CO-OP Play & I'm having all characters left

Fixed in https://github.com/tmarenko/mff_auto/commit/221e4b2fbfe4d1b9c03b2d190ca8d23c57c3724b

**Comment by tmarenko** [comment]
> Bot doesn't click on Co-Op skill while playing World Boss.

Need to see logs. Mine characters are doing fine and casting Co-op skill.

> If stages are completed bot start play again In training mode instead of quitting

Need logs too. Did you setup "Stages" counter more than available stages for World Boss?

**Comment by tmarenko** [comment]
> If Normal mode is selected in Mission Queue and if Ultimate stage is selected then bot will start playing Ultimate stage instead of normal mode.

Fixed in https://github.com/tmarenko/mff_auto/commit/7544a63f15030797ab76e230a0e94b256a1929ad

**Comment by dbzdivik** [comment]
Regarding Co-oP play Missions, Mission quest can easily be readable via tesseract and can assign settings as Daily Trivia have an answer. The same can go for mission Fixed Team can be assigned but there is a hunch you have to train Tesseract to recognize characters.

**Comment by tmarenko** [comment]
> Regarding Co-oP play Missions, Mission quest can easily be readable via tesseract and can assign settings as Daily Trivia have an answer. The same can go for mission Fixed Team can be assigned but there is a hunch you have to train Tesseract to recognize characters.

True. I'm looking for it right now.

> 2. Bot doesn't click on Co-Op skill while playing World Boss.
> 3. If stages are completed bot start play again In training mode instead of quitting

Have you encountered these problems since?

**Comment by dbzdivik** [comment]
2. If stages are completed bot start play again In training mode instead of quitting
> 
> Have you encountered these problems since?
