### ISSUE TITLE
Set teams for various stages from a properties or json file & auto story & shadowland modes

### ISSUE THREAD

**Issue by akshaypune** [tmarenko/mff_auto#40]
Kudos on the beautifully designed and executed bot!

It would be awesome if we could set teams for various Shadowland or Story mode stages using a properties or JSON file and set that team in game using scripts. Also, an auto story and shadowland modes using these scripts and json/properties files would be really helpful.

**Comment by tmarenko** [comment]
> Story mode

I believe almost any Story mode require more control of character. Sometime you need to evade red areas, collect items, etc. `ManualBattleBot` (https://github.com/tmarenko/mff_auto/blob/master/lib/game/battle_bot.py#L229) only can cast abilities and move in circles.
I'm not sure if any of Story modes is doable with this.

> Shadowland 

I've been thinking about how I could automate shadowland, but there haven't been any good ideas over the past year.
This mode requires you to choose characters and room with different rules, use character from last season or choose new ones, scroll over character list, some later stages 30-35 require special characters that should haven't been used at the start, etc. => so much tasks and conditions.
Without a way to do a proper scroll and recognize characters it's a pain to automate this mode.
I still have no idea how to implement this in general way.

**Comment by tmarenko** [comment]
Shadowland was added in https://github.com/tmarenko/mff_auto/commit/ab00b11955ee2329d81b2cd46af74848cf331d88
Released in https://github.com/tmarenko/mff_auto/releases/tag/0.9.0
