### ISSUE TITLE
IGN in Korean not displayed properly

### ISSUE THREAD

**Issue by akshaypune** [tmarenko/mff_auto#41]
Ign ![image](https://user-images.githubusercontent.com/21168386/131629780-f55bd303-df64-48f5-85b3-9fd414deaa10.png)
displayed as 
![image](https://user-images.githubusercontent.com/21168386/131629863-f761a2cf-be92-4dd8-9c4d-6bf6b6c81f4e.png)

**Comment by tmarenko** [comment]
This project uses Tesseract OCR with English language: https://github.com/tmarenko/mff_auto/blob/master/lib/functions.py#L31-L34

Displaying proper IGN isn't a mandatory feature. IGN is never used anywhere inside the code of any gamemode so it doesn't matter if it displayed properly or improperly.
 
Adding Korean language (additional 20Mb in size for `.traineddata` file) only for this minor feature isn't worth it.
