### ISSUE TITLE
Latest update broke timeline battle.

### ISSUE THREAD

**Issue by jeisonfura** [tmarenko/mff_auto#5]
After selecting team, it will move to next phase.

2020-09-29 10:14:52,465 - timeline - INFO - Timeline Battle: 10 stages available
2020-09-29 10:15:05,727 - timeline - DEBUG - Selecting team: TL_SELECT_TEAM_1
2020-09-29 10:15:06,854 - game - DEBUG - Loading circle is on screen.
2020-09-29 10:15:07,281 - queue_manager - DEBUG - Skipping queue item: SQUAD BATTLE

**Comment by tmarenko** [comment]
That's odd. Last time any "Timeline Battle"-related code was changed is 3 weeks ago. Nothing new was introduced.

It probably can't find FIGHT button here:
https://github.com/tmarenko/mff_auto/blob/master/lib/game/missions/timeline.py#L88
but I don't know why. I've tested this button in 720p/1080p/1440p even with LOW graphic settings and it works fine.

What's your display resolution and graphic settings?

**Comment by jeisonfura** [comment]
Resolution is 1920 × 1080 and graphics is set to Medium. I just switched accounts, and now it's working, so I don't know... 

Good job on bot btw. I found this because I was going to try to create my own, but this is way better than anything I could have made myself.

**Comment by tmarenko** [comment]
> Good job on bot btw. I found this because I was going to try to create my own, but this is way better than anything I could have made myself.

Thank you

> Resolution is 1920 × 1080 and graphics is set to Medium. I just switched accounts, and now it's working, so I don't know...

I'll close this issue then. Maybe more logging in timeline's module will help to find what was the issue.
