### ISSUE TITLE
[Feature Request] Wait for energy like Wait for Boost points

### ISSUE THREAD

**Issue by FDC18** [tmarenko/mff_auto#53]
Self explanatory, just it would be nice if we could set up an arbitrary amount of energy to wait for.

**Comment by tmarenko** [comment]
Added in https://github.com/tmarenko/mff_auto/commit/69c384ace489c9f9b63bac9167c3b93fcc178365
Released in https://github.com/tmarenko/mff_auto/releases/tag/0.9.4
