### ISSUE TITLE
Bot no longer starts

### ISSUE THREAD

**Issue by jeisonfura** [tmarenko/mff_auto#8]
When running start.bat, it closes shortly after. Here is the output from the log file:

2020-10-01 09:36:58,695 - updater - INFO - Loaded version: mff_auto=0.6.2, game=6.4.1, updater=1.0.1
2020-10-01 09:36:59,796 - updater - INFO - Current version 0.6.2 is up to date for MFF 6.4.1.
2020-10-01 09:37:00,690 - root - DEBUG - Creating 4 Tesseract API(s) with 'eng' language.
2020-10-01 09:37:02,914 - root - DEBUG - Creating 2 Tesseract API(s) with 'mff+eng' language.

After that, an error quickly displays and the command line closes.

**Comment by dbzdivik** [comment]
+1

**Comment by tmarenko** [comment]
Add this line:
`@pause`
at the end of `start.bat` file. And then copy the output here.

**Comment by dbzdivik** [comment]
![image](https://user-images.githubusercontent.com/7036189/94839159-41949880-0434-11eb-96ff-35b9cf200522.png)

**Comment by tmarenko** [comment]
Oh, sure. I forgot that auto-update can't install new modules. 
You should download last build then: https://github.com/tmarenko/mff_auto/releases/tag/0.6.2

**Comment by tmarenko** [comment]
I've updated version file to prevent auto-update from 0.6.1 to 0.6.2
https://github.com/tmarenko/mff_auto/commit/8affe7e3faa12f641712de65b0551e6ec215791b

**Comment by dbzdivik** [comment]
> I've updated version file to prevent auto-update from 0.6.1 to 0.6.2
> [8affe7e](https://github.com/tmarenko/mff_auto/commit/8affe7e3faa12f641712de65b0551e6ec215791b)

Might wanna rebuild the release again as it still contains updater version 1.0.1

**Comment by tmarenko** [comment]
> Might wanna rebuild the release again as it still contains updater version 1.0.1

Done
